INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO users (name, age) VALUES ("steve", 10);
INSERT INTO projects (title, category, funding_goal,start_date, end_date) VALUES ("Holy Moly", "B Active", 100000, 10-20-19, 10-20-20);
INSERT INTO projects (title, category, funding_goal,start_date, end_date) VALUES ("Holy Moly", "B Active", 100000, 10-20-19, 10-20-20);
INSERT INTO projects (title, category, funding_goal,start_date, end_date) VALUES ("Holy Moly", "B Active", 100000, 10-20-19, 10-20-20);
INSERT INTO projects (title, category, funding_goal,start_date, end_date) VALUES ("Holy Moly", "B Active", 100000, 10-20-19, 10-20-20);
INSERT INTO projects (title, category, funding_goal,start_date, end_date) VALUES ("Holy Moly", "B Active", 100000, 10-20-19, 10-20-20);
INSERT INTO projects (title, category, funding_goal,start_date, end_date) VALUES ("Holy Moly", "B Active", 100000, 10-20-19, 10-20-20);
INSERT INTO projects (title, category, funding_goal,start_date, end_date) VALUES ("Holy Moly", "B Active", 100000, 10-20-19, 10-20-20);
INSERT INTO projects (title, category, funding_goal,start_date, end_date) VALUES ("Holy Moly", "B Active", 100000, 10-20-19, 10-20-20);
INSERT INTO projects (title, category, funding_goal,start_date, end_date) VALUES ("Holy Moly", "B Active", 100000, 10-20-19, 10-20-20);
INSERT INTO projects (title, category, funding_goal,start_date, end_date) VALUES ("Holy Moly", "B Active", 100000, 10-20-19, 10-20-20);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
